project_name: certificate-init-container

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
- goos: linux
  goarch: amd64
  use: buildx
  dockerfile: Dockerfile
  image_templates:
    - "docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "docker.io/twdps/{{ .ProjectName }}:latest-amd64"
  build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

- goos: linux
  goarch: ard64
  use: buildx
  dockerfile: Dockerfile
  image_templates:
    - "docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-arm64"
    - "docker.io/twdps/{{ .ProjectName }}:latest-arm64"
  build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: docker.io/twdps/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-amd64
  - docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-arm64
- name_template: docker.io/twdps/{{ .ProjectName }}:latest
  image_templates:
  - docker.io/twdps/{{ .ProjectName }}:latest-amd64
  - docker.io/twdps/{{ .ProjectName }}:latest-arm64

# signs:
#   - cmd: cosign
#     stdin: '{{ .Env.COSIGN_PWD }}'
#     args: ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
#     artifacts: all
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
source:
  # https://goreleaser.com/customization/source/
  enabled: true
