---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: publications-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
      version: v1
  template:
    metadata:
      labels:
        app: ubuntu
        version: v1
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: tls
            mountPath: /etc/tls
      initContainers:
      - image: twdps/certificate-init-container:0.0.5
        imagePullPolicy: IfNotPresent
        name: cert-init
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        args:
          - "-cert-dir=/etc/tls"
          - "-namespace=$(NAMESPACE)"
          - "-pod-ip=$(POD_IP)"
          - "-pod-name=$(POD_NAME)"
          - "-service-names=publications-dev-slp"
        volumeMounts:
          - name: tls
            mountPath: /etc/tls
      volumes:
      - name: tls
        emptyDir: {}
